cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'amazeeio/cachalot'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'nvm'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'
brew 'yarn'
brew 'docker'
brew 'docker-machine'
brew 'cachalot'
brew 'cmake'
brew 'asciinema'
brew 'rethinkdb'

cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'seashore'
cask 'slack'
cask 'vlc'
